config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  # get 'pages/home'
  # get 'users/new'
  resources :users#, only: [:new, :create]
  resources :sessions #, only: [:new, :create, :destroy]
  resources :items

  resources :user_item

  # resources :items do
  # 	resources :user_item
  # end
  resources :user_item
  root  'pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin' , to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/electronics', to: 'items#electronics', as: 'electronics',via: 'get'
  match '/mobiles', to: 'items#mobiles', as: 'mobiles',via: 'get'
  match '/vehicles', to: 'items#vehicles', as: 'vehicles',via: 'get'
  match '/title', to: 'items#title', as: 'title',via: 'get'
  match '/price', to: 'items#price', as: 'price',via: 'get'


  match '/search', to: 'pages#search', as: 'search', via:['get','post']
  
  
  match '/likes/:id', to: 'items#likes', as: 'like',via: ['get','post']
  match '/unlikes/:id', to: 'items#unlikes', as: 'unlike',via: ['get','post','delete']



end

app/models/item.rb
class Item < ApplicationRecord
	  has_many :user_item, dependent: :destroy
    has_many :user  ,through: :user_item


	validates :name, presence: true
	
	validates :price, presence: true

	validates :status, presence: true

	validates :category, presence: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter:require_login
	
	def new
		@item=Item.new
	end
	
	def create
    @item=Item.new(item_params)
    if @item.save
    	flash[:success] = 'Item Added Successfully'
      redirect_to root_path, :notice => "Item Added"
    else
      render 'new'
    end
	end
	def index(category:'non')
		# @items=Item.all
		# @items=@items.sort_by{|a| a[:name]}
		if(category=='non')
		  @items = Item.paginate(page: params[:page], :per_page => 2)  
		else
			# @items = Item.paginate(page: params[:page], :per_page => 2)

		end  
	end
	def show
		@item=Item.find(params[:id])
	end
	def edit
		@item=Item.find(params[:id])
	end
  def update
    @item =Item.find(params[:id])
    if @item.update_attributes(item_params)
      if @item.update_attributes(item_params)
      	flash[:success] = "Item updated"
      	redirect_to @item
    	else
    		flash.now[:warning] = 'Enter complete information'
      	render 'edit'
    	end
  	end
	end
	def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted."
    redirect_to items_url
  end
  def electronics
  	@item =Item.where(category:'electronics')
    @items = @item.paginate(page: params[:page], :per_page => 6)
	end
	def mobiles
  	@item =Item.where(category:'mobiles')
    @items = @item.paginate(page: params[:page], :per_page => 6)
	end
	def vehicles
  	@item =Item.where(category:'vehicles')
    @items = @item.paginate(page: params[:page], :per_page => 6)
	end
	def title
  	@item =Item.all.order(:name)
     @items = @item.paginate(page: params[:page], :per_page => 6)
	end
	def price
  	 @item =Item.all.order(:price)
      @items = @item.paginate(page: params[:page], :per_page => 1)
	end
	def likes
		@item=Item.find(params[:id])
		@user_item=UserItem.new(user_id: current_user.id,item_id:@item.id)
		if @user_item.save
			respond_to do |format|
      format.html { redirect_to items_path }
      format.js
    end
			flash[:success]="Item liked"
		end
	end
	def unlikes
		@user_item=UserItem.where(user_id: current_user.id , item_id: params[:id])
		# @user_item=UserItem.new(user_id: current_user.id,item_id:@item.id)
		i=@user_item.ids
	  UserItem.destroy(i[0])
		respond_to do |format|
    	format.html { redirect_to items_path }
    	format.js
			flash[:success]="Item unliked"
		end
	end
	helper_method :electronics
	helper_method:mobile
	helper_method:Vehicle
	helper_method :title
	helper_method :price
	helper_method :likes
	private
		def item_params
			params.require(:item).permit(:name,:price,:image,:Location,:description,:specification,:category,:status)
		end

end

app/helpers/items_helper.rb
module ItemsHelper	
	# def electronics
 #  		@item =Item.where(category:'electronics')
 #     	@items = @item.paginate(page: params[:page], :per_page => 6)
	# end
	# helper_method :electronics
end

app/views/items/_category.html.erb
<%= form_tag(search_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>
<br>
<br>
<br>
<br>


<ul>
	Show BY Category
		<li><%= link_to "All Items",items_path %></li><br>
		<li><%= link_to "Electronics", electronics_path%></li><br>
   	<li><%= link_to "Mobiles",mobiles_path %></li><br>
    <li><%= link_to "Vehicles",vehicles_path %></li><br>
</ul>
<ul>
	<b>Order By</b>
	<li><%= link_to "Title", title_path%></li><br>
  <li><%= link_to "Price", price_path%></li><br>


</ul>
 

app/views/items/_itemAdd.html.erb
	<%= render 'shared/error_messages' , object: f.object%>

	<%= f.label :name %>
	<%= f.text_field :name %><br>
				 
	<%= f.label :image %>
	<%= f.file_field :image %>


	<%= f.label :price %>
	<%= f.text_field :price%><br>

	<%= f.label :status%><p>Available/sold<p>
	<%= f.text_field :status%><br>

	<%= f.label :specification %>
	<%= f.text_field :specification %><br>

	<%= f.label :description %>
	<%= f.text_field :description%><br>

	<%= f.label :Location %>
	<%= f.text_field :Location%><br>

  <%= f.label :category %><br />
  <%= f.select(:category,options_for_select([['electronics'],['vehicles'],['mobiles']])) %>

app/views/items/_itemUpdate.html.erb
	<%= render 'shared/error_messages' , object: f.object%>

	<%=image_tag @item.image.url(:thumb) %><br>

	<%= f.label :name %>
	<%= f.text_field :name %><br>
				 
	<%= f.label :image %>
	<%= f.file_field :image %>


	<%= f.label :price %>
	<%= f.text_field :price%><br>

	<%= f.label :status%><p>Available/sold<p>
	<%= f.text_field :status%><br>

	<%= f.label :specification %>
	<%= f.text_field :specification %><br>

	<%= f.label :description %>
	<%= f.text_field :description%><br>

	<%= f.label :Location %>
	<%= f.text_field :Location%><br>

  <%= f.label :category %><br />
  <%= f.select(:category,options_for_select([['electronics'],['vehicles'],['mobiles']])) %>

app/views/items/_itemshow.html.erb
	<%= render 'shared/error_messages' , object: f.object%>

	<%=image_tag @item.image.url(:thumb) %><br>
			
	<%= f.label :name %>
	<%= f.text_field :name ,:readonly=>true%><br>
				 
	


	<%= f.label :price %>
	<%= f.text_field :price ,:readonly=>true%><br>

	<%= f.label :status%>
	<%= f.text_field :status ,:readonly=>true%><br>

	<%= f.label :specification %>
	<%= f.text_field :specification ,:readonly=>true%><br>

	<%= f.label :description %>
	<%= f.text_field :description ,:readonly=>true%><br>

	<%= f.label :Location %>
	<%= f.text_field :Location ,:readonly=>true%><br>

  <%= f.label :category %><br />
  <%=f.text_field :category,:readonly=>true  %>

app/views/items/edit.html.erb
<% provide(:title, 'Updaate Item ') %>
<h1>Update Item</h1>

<div class="row">
  <div class="span6 offset3">
     <%= form_for(@item, html:{multipart:true}) do |f| %>
     <%= render 'itemUpdate', f: f %>

     <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/items/electronics.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">All Items</h1>

 			<%= will_paginate%></br></br>
 		<!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!-- 						<ul class="items">
 -->  <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
				<br>
				<br>

  	  <% end %>
<!-- 					</ul>
 --></br></br>
 			<%= will_paginate%>
 
		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>

app/views/items/index.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">All Items</h1>

			<%= will_paginate%></br></br>
			<!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!-- 						<ul class="items">
 -->  <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
    		<br>
 			  <br>
 				<p>Total Likes : <%=UserItem.where(item_id:item.id).count %><p>
				<br>
				<% @i=UserItem.where(user_id: current_user.id,item_id:item.id)%>
				<% if UserItem.exists?(@i).present? %>
 				<%= button_to 'unLike', unlike_path(item) %>

 				<br>
 				<%else%>
 					<%= button_to 'Like', like_path(item) %>
 				<%end%>
 			  <br>

  	  <% end %>
<!-- 					</ul>
 --></br></br>
			<%= will_paginate%>

		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>

app/views/items/mobiles.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">Mobiles</h1>

 			<%= will_paginate%></br></br>
 			<!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!-- 						<ul class="items">
 -->  <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
				<br>
				<br>

  	  <% end %>
<!-- 					</ul>
 --></br></br>
 			<%= will_paginate%>
 
		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>

app/views/items/new.html.erb
<% provide(:title, 'Add Items') %>
<h1>Add Item</h1>

<div class="row">
  <div class="span6 offset3">
     <%= form_for(@item, html:{multipart:true}) do |f| %>
     <%= render 'itemAdd', f: f %>

      <%= f.submit "Add Item", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/price.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">All Items(Order By Price)</h1>


    <%= will_paginate%></br></br>
     <!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!--            <ul class="items">
 --> 
 <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
				<br>
				<br>

  	  <% end %>
</br></br>

      <%= will_paginate%>
 

		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>

app/views/items/show.html.erb
<% provide(:title, 'Item Detail') %>

<h1>Item Detail</h1>

<div class="row">
  <div class="span6 offset3">
     <%= form_for(@item, html:{multipart:true}) do |f| %>
     <%= render 'itemshow', f: f %>
     <%if logged_in?%>
     <ul> <li><%= link_to "Update Item", edit_item_path(@item)%></li></ul>
    <ul> <li><%= link_to "Delete Item", @item, method: :delete, data: { confirm: "You sure?" }%></li>  </ul>
     <%end%>
    <% end %>
  </div>
</div>

app/views/items/title.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">Title(Order By Title)</h1>

		<%= will_paginate%></br></br>
 		<!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!-- 						<ul class="items">
 -->  <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
				<br>
				<br>

  	  <% end %>
<!-- 					</ul>
 --></br></br>
		<%= will_paginate%>

		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>

app/views/items/vehicles.html.erb
<div class="container-fluid">
  <div class="row">
  	<div class="col-sm-3 col-md-4 col-lg-4"style="padding-top: 170px" >
      
      <%= render 'items/category' %>
    </div>
 		<div class="col-sm-9 col-md-8 col-lg-8" style="padding-left: 80px" >
		  <% provide(:title, 'All Items') %>
			<h1 style="padding-top: 50px;padding-right: 430px">Vehicles</h1>

			<%= will_paginate%></br></br>
 			<!-- @items.paginate(page: params[:page], :per_page=>1 ) -->

<!-- 						<ul class="items">
 -->  <% @items.each do |item| %>
    
    		<%=image_tag item.image.url(:thumb) %><br>
    		<%= link_to item.name, item_path(item) %><br>
    		<%=link_to item.price,item, :disabled=>true %><br>
    		<%= link_to item.category, item %><br>
				<br>
				<br>

  	  <% end %>
<!-- 					</ul>
 --></br></br>
 			<%= will_paginate%>
 
		</div> 
		<!--	</div> -->
		<!-- </div> -->   
		
  </div>
<!-- s -->
</div>