config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  # get 'pages/home'
  # get 'users/new'
  resources :users#, only: [:new, :create]
  resources :sessions #, only: [:new, :create, :destroy]
  resources :items

  resources :user_item

  # resources :items do
  # 	resources :user_item
  # end
  resources :user_item
  root  'pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin' , to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'
  match '/electronics', to: 'items#electronics', as: 'electronics',via: 'get'
  match '/mobiles', to: 'items#mobiles', as: 'mobiles',via: 'get'
  match '/vehicles', to: 'items#vehicles', as: 'vehicles',via: 'get'
  match '/title', to: 'items#title', as: 'title',via: 'get'
  match '/price', to: 'items#price', as: 'price',via: 'get'


  match '/search', to: 'pages#search', as: 'search', via:['get','post']
  
  
  match '/likes/:id', to: 'items#likes', as: 'like',via: ['get','post']
  match '/unlikes/:id', to: 'items#unlikes', as: 'unlike',via: ['get','post','delete']



end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav class="nav pull-right">
    <ul>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Market Place", '#', id: "logo" %>
      <nav>         
        <ul class="nav pull-right">
        
        <ul><li><%= link_to "Home",   root_path %></li></ul>
        <li><%if logged_in?%></li>
        <li class="nav pull-left"><%= current_user.name %></li>
        <ul> <li><%= link_to "Sign Out", signout_path%></li></ul>
        <ul> <li><%= link_to "Profile Update", edit_user_path(current_user)%></li></ul>
        <ul> <li><%= link_to "Profile", user_path(current_user)%></li></ul>
        <ul> <li><%= link_to "Add Items", new_item_path%></li></ul>
        <ul> <li><%= link_to "Items path", items_path%></li></ul>
        <%else%>
        <ul> <li><%= link_to "Sign Up", signup_path %></li></ul>

        <ul> <li><%= link_to "Sign in", signin_path%></li></ul>


        <%end%>
        </ul>


       </nav> 
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9] -->
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<!-- [endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="container-fluid">
        <div class="row-fluid">
           <div class="span10">
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
 
            <%= yield %>
          </div>
          <%= render 'layouts/footer' %>
          <%= debug(params) if Rails.env.development? %>
        </div>
      </div>
    </div>
  </body>
</html>